### ISSUE TITLE
Help:Can't works in raspberry pi2 in ubuntu 15.04

### ISSUE THREAD

**Issue by joole** [invokr/c9.ide.language.cpp#3]
I compiled the node v0.12.9 with gnu 4.9 on rpi2 and the system is ubuntu 15.04 mate, then, install the c9.ide.language.cpp in the local is ;
"plugins/c9.ide.language.cpp/cpp" 
the c9 front webide says it's ok,but no effective on cpp file,can you help me ?

**Comment by invokr** [comment]
Hi joole,
I can't help you unless you post a specific error. Look at the ocnsole output (js and commandline) and see if anything fails to initialize. It not having any effect on C++ files means that the plugin probably didn't register the server or worker component.

I just recently created a docker image that includes the C++ plugin: https://github.com/invokr/cloud9-docker-cpp
Using that might be easier than figuring out whats wrong with your setup.
