### ISSUE TITLE
require('clang_tool') in cpp_server.js failing with Error: Module did not self-register.

### ISSUE THREAD

**Issue by flackr** [invokr/c9.ide.language.cpp#4]
Hi, I'm trying to run this on my local c9sdk instance and I can't figure out why, but it fails in cpp_server.js with the following output on the console:

VFS Exception in function 'extend':
 Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at module.exports (/home/flackr/Downloads/c9sdk/plugins/c9.ide.language.cpp/cpp_server.js:10:22)
    at exec (/home/flackr/Downloads/c9sdk/node_modules/vfs-local/localfs.js:2396:13)
    at Object.extend (/home/flackr/Downloads/c9sdk/node_modules/vfs-local/localfs.js:2363:13)
    at Domain.<anonymous> (/home/flackr/Downloads/c9sdk/node_modules/vfs-local/localfs.js:234:30)
    at Domain.run (domain.js:197:16)
Scheduling process exit

This error keeps repeating forever. The strange thing is I can run demo.js from clang_tool, even changing the require to use the module name instead of path to be identical to cpp_server.js and it works when run from the command-line. The failure seems to be specific to when it's loaded through this c9 plugin.

Let me know if there's any particular details I can provide that would help. I'm running node version v0.10.25 though I've also tried v4.2.6 with the same error.

**Comment by invokr** [comment]
Hi Robert,

I had the same issue as you some time in the past. If I remember correctly, it had to do with the nodejs version I was using. You need to compile the module with the same version you use to run C9.
Try 0.12, that's what I'm using in the [Docker Image](https://github.com/invokr/cloud9-docker-cpp).

Robin

**Comment by flackr** [comment]
I did try node.js 0.12 from https://nodejs.org/dist/v0.12.0/node-v0.12.0-linux-x64.tar.gz and rebuilt the modules using npm rebuild but I ran into the same error. I guess I should try with the Docker script though I'm only running Ubuntu 14.04 LTS. How do you use the Docker image?

**Comment by invokr** [comment]
If you want to run multiple node versions without getting headaches, I recommend [nvm](https://github.com/creationix/nvm). 

As for docker, install the latest version as per their official [documentation](https://docs.docker.com/engine/installation/linux/ubuntulinux/).

```
# Pull the container. It's already build and I confirmed it is working yesterday
docker pull invokr/cloud9-cpp

# Run the container without mounting a workspace, access via localhost:8080
docker run -d -p 8080:8080 invokr/cloud9-cpp
docker ps # this will list the container id
docker kill <id> # this will stop it

# Mount an existing folder as a workspace
docker run -d -p 8080:8080 -v /path/on/host:/workspace invokr/cloud9-cpp

# Use this to debug. Modify c9 in /c9sdk and the plugin in /root/.c9/plugins/
docker run -it -p 8080:8080 invokr/cloud9-cpp /bin/bash
/init.sh # within the container. 
```

The container will copy over some project and user settings if they are not found in the workspace. If you mount a workspace where those files exist, they will not be overwritten. Make sure the first three options under `experimental` are activated. All files that are not within a mounted folder will be destroyed when the container is stopped.

**Comment by flackr** [comment]
Thanks, using node v0.12.9 from nvm did the trick. I had to recreate everything for some reason but once I did that everything just worked. Thanks for the help.

I wonder if there's a nice clean way to catch the require error and give a nice message to help people like me who try this in the future. Maybe a try/catch around the require?

**Comment by invokr** [comment]
Overall, native plugins feel extremely fragile, so I don't know if there is a really good way to get this stable, even with better debugging. `libclang` isn't the most stable piece of software, too, so maybe implementing a client for [ycmd](https://github.com/Valloric/ycmd), which has excellent error handling, would be a better way to get diagnostics and code completion.
